name: PHP Insights CI GitHub Action

on: [push, pull_request]

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    steps:
      - name: Run PHP Insights
        run: php artisan insights --no-interaction --min-quality=70 --min-complexity=80 --min-architecture=75 --min-style=95
