name: Laravel Pint CI GitHub Action

on: [pull_request, push]

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@0.1.0
        with:
          preset: laravel
          verboseMode: true
          testMode: true
